//
// Created by Jedrzej Kosinski on 8/28/2017.
//

#ifndef SCRAPCONTROLLER_SCRAPDEFINITIONS_H
#define SCRAPCONTROLLER_SCRAPDEFINITIONS_H

// ScrapMotorControl constants
#define SCRAPMOTORCONTROL_MINPOWER 50

// ScrapController constants
#define SCRAPCONTROLLER_ENCTOLERANCE 5
#define SCRAPCONTROLLER_SLOWDOWNTHRESH 200
#define SCRAPCONTROLLER_MINSLOWPOWER 120
#define SCRAPCONTROLLER_MINENCSPEED 200
#define SCRAPCONTROLLER_MAXENCSPEED 2000

// ScrapDualController constants
#define SCRAPDUALCONTROLLER_DIFFTOLERANCE 40
#define SCRAPDUALCONTROLLER_ENCTOLERANCE 5
#define SCRAPDUALCONTROLLER_SLOWDOWNTHRESH1 500
#define SCRAPDUALCONTROLLER_SLOWDOWNTHRESH2 500
#define SCRAPDUALCONTROLLER_MINSLOWPOWER1 65
#define SCRAPDUALCONTROLLER_MINSLOWPOWER2 65
#define SCRAPDUALCONTROLLER_MINENCSPEED 200
#define SCRAPDUALCONTROLLER_MAXENCSPEED 1400
#define SCRAPDUALCONTROLLER_ENCSPEEDBALANCE 10


#endif //SCRAPCONTROLLER_SCRAPDEFINITIONS_H
